"""Restaura diacriticos no texto editorial do TD, preservando codigo e URLs."""

from pathlib import Path
import re


PATH = Path(__file__).resolve().parents[1] / "artigo" / "TD_clusterizacao_noticias_pf.md"

REPLACEMENTS = {
    "Apendice": "Apêndice",
    "Introducao": "Introdução",
    "Conclusao": "Conclusão",
    "Funcao": "Função",
    "Policia": "Polícia",
    "Publicacao": "Publicação",
    "Titulo": "Título",
    "Subtitulo": "Subtítulo",
    "Agencia": "Agência",
    "Nacional": "Nacional",
    "Uniao": "União",
    "orgao": "órgão",
    "orgaos": "órgãos",
    "organizacao": "organização",
    "organizacoes": "organizações",
    "tematica": "temática",
    "tematicas": "temáticas",
    "tematico": "temático",
    "tematicos": "temáticos",
    "classificacao": "classificação",
    "classificacoes": "classificações",
    "revisao": "revisão",
    "revisoes": "revisões",
    "propoe": "propõe",
    "autonoma": "autônoma",
    "autonomo": "autônomo",
    "auditavel": "auditável",
    "auditaveis": "auditáveis",
    "clusterizacao": "clusterização",
    "consolidacao": "consolidação",
    "semantica": "semântica",
    "semanticas": "semânticas",
    "geracao": "geração",
    "expressoes": "expressões",
    "periodica": "periódica",
    "arvore": "árvore",
    "nao": "não",
    "residuos": "resíduos",
    "deterministica": "determinística",
    "deterministicas": "determinísticas",
    "deterministico": "determinístico",
    "deterministicos": "determinísticos",
    "aplicacao": "aplicação",
    "aplicacoes": "aplicações",
    "noticia": "notícia",
    "noticias": "notícias",
    "publica": "pública",
    "publicas": "públicas",
    "heterogenea": "heterogênea",
    "heterogeneas": "heterogêneas",
    "operacao": "operação",
    "operacoes": "operações",
    "atualizacao": "atualização",
    "atualizacoes": "atualizações",
    "canonico": "canônico",
    "canonica": "canônica",
    "canonicos": "canônicos",
    "canonicas": "canônicas",
    "reducao": "redução",
    "instituicoes": "instituições",
    "institucional": "institucional",
    "institucionais": "institucionais",
    "informacao": "informação",
    "informacoes": "informações",
    "seguranca": "segurança",
    "observatorios": "observatórios",
    "relatorios": "relatórios",
    "descricoes": "descrições",
    "ocorrencias": "ocorrências",
    "tecnicos": "técnicos",
    "politicas": "políticas",
    "evidencias": "evidências",
    "analise": "análise",
    "analitica": "analítica",
    "analiticas": "analíticas",
    "continuo": "contínuo",
    "continua": "contínua",
    "continuos": "contínuos",
    "continuas": "contínuas",
    "variacao": "variação",
    "repeticao": "repetição",
    "mudancas": "mudanças",
    "proprios": "próprios",
    "codigos": "códigos",
    "escalavel": "escalável",
    "automatica": "automática",
    "ruido": "ruído",
    "instaveis": "instáveis",
    "tambem": "também",
    "documentacao": "documentação",
    "extracao": "extração",
    "nomeacao": "nomeação",
    "previsivel": "previsível",
    "reprodutivel": "reprodutível",
    "reprodutiveis": "reprodutíveis",
    "tensao": "tensão",
    "excecoes": "exceções",
    "discussao": "discussão",
    "transparencia": "transparência",
    "inferencia": "inferência",
    "inferencia": "inferência",
    "constituirem": "constituírem",
    "secao": "seção",
    "secoes": "seções",
    "criterios": "critérios",
    "limitacoes": "limitações",
    "teorico": "teórico",
    "familias": "famílias",
    "representacoes": "representações",
    "tecnicas": "técnicas",
    "rotulos": "rótulos",
    "colecoes": "coleções",
    "previa": "prévia",
    "combinacao": "combinação",
    "comparacao": "comparação",
    "fundacao": "fundação",
    "decisao": "decisão",
    "decisoes": "decisões",
    "juridica": "jurídica",
    "acao": "ação",
    "acoes": "ações",
    "saude": "saúde",
    "trafico": "tráfico",
    "criancas": "crianças",
    "corrupcao": "corrupção",
    "falsificacao": "falsificação",
    "ingestao": "ingestão",
    "fracao": "fração",
    "parametros": "parâmetros",
    "titulo": "título",
    "subtitulo": "subtítulo",
    "ilicitos": "ilícitos",
    "proximas": "próximas",
    "proximos": "próximos",
    "distincao": "distinção",
    "unico": "único",
    "saida": "saída",
    "saidas": "saídas",
    "disponiveis": "disponíveis",
    "sugestoes": "sugestões",
    "logica": "lógica",
    "interpretacao": "interpretação",
    "relacao": "relação",
    "memoria": "memória",
    "metodo": "método",
    "proporcao": "proporção",
    "metricas": "métricas",
    "funcoes": "funções",
    "rotulagem": "rotulagem",
    "construcao": "construção",
    "diferenca": "diferença",
    "integracao": "integração",
    "contribuicao": "contribuição",
    "dependencia": "dependência",
    "reorganizacao": "reorganização",
    "validacao": "validação",
    "execucao": "execução",
    "disponivel": "disponível",
    "razao": "razão",
    "especifica": "específica",
    "pressao": "pressão",
    "pos_quarentena": "pos_quarentena",
    "padrao": "padrão",
    "padroes": "padrões",
    "exploratoria": "exploratória",
    "exploratorio": "exploratório",
    "reutilizaveis": "reutilizáveis",
    "empirica": "empírica",
    "empirico": "empírico",
    "verificacao": "verificação",
    "metodologico": "metodológico",
    "metodologica": "metodológica",
    "construida": "construída",
    "necessario": "necessário",
    "necessaria": "necessária",
    "familia": "família",
    "aquisicao": "aquisição",
    "dominio": "domínio",
    "dominios": "domínios",
    "sao": "são",
    "recorrencia": "recorrência",
    "recorrencias": "recorrências",
    "distribuicao": "distribuição",
    "demonstracao": "demonstração",
    "estabilidade": "estabilidade",
    "possivel": "possível",
    "possiveis": "possíveis",
    "especifico": "específico",
    "especificos": "específicos",
    "genericos": "genéricos",
    "generico": "genérico",
    "separacao": "separação",
    "dimensoes": "dimensões",
    "decomposicao": "decomposição",
    "atributo": "atributo",
    "referencias": "referências",
    "ha": "há",
    "transferivel": "transferível",
    "intervencao": "intervenção",
    "interpretaveis": "interpretáveis",
    "interpretavel": "interpretável",
    "redacao": "redação",
    "exploratorias": "exploratórias",
    "util": "útil",
    "ja": "já",
    "supervisao": "supervisão",
    "programatica": "programática",
    "programaticos": "programáticos",
    "ate": "até",
    "explicito": "explícito",
    "rigidas": "rígidas",
    "topicos": "tópicos",
    "esforco": "esforço",
    "federacao": "federação",
    "metadados": "metadados",
    "obrigatorios": "obrigatórios",
    "divisao": "divisão",
    "visualizacao": "visualização",
    "reforca": "reforça",
    "agregacao": "agregação",
    "precisao": "precisão",
    "taxonomica": "taxonômica",
    "proliferacao": "proliferação",
    "defensavel": "defensável",
    "aceitavel": "aceitável",
    "atuacao": "atuação",
    "classicas": "clássicas",
    "principio": "princípio",
    "associada": "associada",
    "estaveis": "estáveis",
    "comparavel": "comparável",
    "reutilizavel": "reutilizável",
    "dificil": "difícil",
    "alem": "além",
    "alteracoes": "alterações",
    "residuo": "resíduo",
    "definicao": "definição",
    "composicao": "composição",
    "medio": "médio",
    "media": "média",
    "apos": "após",
    "iteracao": "iteração",
    "iteracoes": "iterações",
    "estavel": "estável",
    "quarentena": "quarentena",
    "ausencia": "ausência",
    "licenca": "licença",
    "mineracao": "mineração",
    "associacao": "associação",
    "prisao": "prisão",
    "apreensao": "apreensão",
    "representacao": "representação",
    "pratica": "prática",
    "apuracao": "apuração",
    "participacao": "participação",
    "regioes": "regiões",
    "municipios": "municípios",
    "diligencias": "diligências",
    "proprietarios": "proprietários",
    "autorizacao": "autorização",
    "conteineres": "contêineres",
    "poderao": "poderão",
    "evidencia": "evidência",
    "classificador": "classificador",
    "residual": "residual",
}


def match_case(source: str, target: str) -> str:
    if source.isupper():
        return target.upper()
    if source[:1].isupper():
        return target[:1].upper() + target[1:]
    return target


def correct_segment(text: str) -> str:
    # Preserve machine-consumed strings and inline code while correcting prose.
    protected: list[str] = []

    def protect(match: re.Match[str]) -> str:
        protected.append(match.group(0))
        return f"@@PROTECTED_{len(protected)-1}@@"

    text = re.sub(r"https?://[^\s)>\]]+", protect, text)
    text = re.sub(r"`[^`\n]+`", protect, text)
    for source, target in sorted(REPLACEMENTS.items(), key=lambda item: -len(item[0])):
        pattern = re.compile(rf"(?<![\w/-]){re.escape(source)}(?![\w/-])", re.IGNORECASE)
        text = pattern.sub(lambda m, t=target: match_case(m.group(0), t), text)
    text = re.sub(r"\bisto e\b", "isto é", text, flags=re.IGNORECASE)
    text = re.sub(r"\be composta\b", "é composta", text)
    text = re.sub(r"\be uma\b", "é uma", text)
    text = re.sub(r"\be usado\b", "é usado", text)
    text = re.sub(r"\be usada\b", "é usada", text)
    text = re.sub(r"\be o classificador\b", "é o classificador", text)
    text = re.sub(r"\be aplicada\b", "é aplicada", text)
    text = re.sub(r"\be aplicado\b", "é aplicado", text)
    text = re.sub(r"\be convertida\b", "é convertida", text)
    text = re.sub(r"\be convertido\b", "é convertido", text)
    text = re.sub(r"\be a demonstracao\b", "é a demonstração", text)
    text = re.sub(r"\be decomposta\b", "é decomposta", text)
    text = re.sub(r"\be importante\b", "é importante", text)
    text = re.sub(r"\be registrada\b", "é registrada", text)
    text = re.sub(r"\be processada\b", "é processada", text)
    text = re.sub(r"\be tratada\b", "é tratada", text)
    text = re.sub(r"\be tratadas\b", "são tratadas", text)
    text = re.sub(r"\bnao ha\b", "não há", text, flags=re.IGNORECASE)
    for before, after in {
        "classificação e crime": "classificação é crime",
        "O texto esta organizado": "O texto está organizado",
        "não e apenas": "não é apenas",
        "Esses elementos não são": "Esses elementos não são",
        "Essa camada e útil": "Essa camada é útil",
        "e sua auditabilidade": "é sua auditabilidade",
        "metodológica esta em": "metodológica está em",
        "rotulagem e inferência e um": "rotulagem e inferência é um",
        "Discussão esta na": "Discussão está na",
        "trabalho e que": "trabalho é que",
        "e outro eixo": "é outro eixo",
        "também e ajustada": "também é ajustada",
        "contribuição aqui esta": "contribuição aqui está",
        "princípio a classificação": "princípio à classificação",
        "contribuição deste trabalho não esta": "contribuição deste trabalho não está",
        "destaque esta na": "destaque está na",
        "A primeira e a": "A primeira é a",
        "A segunda fase e a": "A segunda fase é a",
        "classificação e o domínio": "classificação é o domínio",
        "metodologia e o documento": "metodologia é o documento",
        "O objetivo não e": "O objetivo não é",
        "e decomposta": "é decomposta",
        "aprendizado residual e o": "aprendizado residual é o",
        "documento e registrado": "documento é registrado",
        "A tarefa da LLM não e": "A tarefa da LLM não é",
        "tema final não e": "tema final não é",
        "resultado principal e a": "resultado principal é a",
        "primeiro e custo": "primeiro é custo",
        "segundo e cobertura": "segundo é cobertura",
        "terceiro e precisão": "terceiro é precisão",
        "quarto e estabilidade": "quarto é estabilidade",
        "quinto e transparência": "quinto é transparência",
        "contribuição central não e": "contribuição central não é",
        "e aplicada empiricamente": "é aplicada empiricamente",
        "pipeline esta preservado": "pipeline está preservado",
        "metadados é uma representação": "metadados e uma representação",
        "processo e difícil": "processo é difícil",
        "premissa central e separar": "premissa central é separar",
        "temática e reorganizada": "temática é reorganizada",
        "base e classificada": "base é classificada",
        "imagem também evidência": "imagem também evidencia",
        "decisão metodológica e definir": "decisão metodológica é definir",
        "A segunda e a reserva": "A segunda é a reserva",
        "O primeiro e custo": "O primeiro é custo",
        "O segundo e cobertura": "O segundo é cobertura",
        "O terceiro e precisão": "O terceiro é precisão",
        "O quarto e estabilidade": "O quarto é estabilidade",
        "O quinto e transparência": "O quinto é transparência",
    }.items():
        text = text.replace(before, after)
    for index, original in enumerate(protected):
        text = text.replace(f"@@PROTECTED_{index}@@", original)
    return text


def main() -> None:
    original = PATH.read_text(encoding="utf-8")
    parts = re.split(r"(```.*?```)", original, flags=re.DOTALL)
    corrected = "".join(part if part.startswith("```") else correct_segment(part) for part in parts)
    PATH.write_text(corrected, encoding="utf-8", newline="\n")


if __name__ == "__main__":
    main()
