from __future__ import annotations

LABEL_ALIASES = {
    "abuso_sexual_infantil": "crimes_contra_crianca",
    "pornografia_infantil": "crimes_contra_crianca",
    "pornografia_infantojuvenil": "crimes_contra_crianca",
    "pornografia_infantil_online": "crimes_contra_crianca",
    "exploracao_sexual_infantil": "crimes_contra_crianca",
    "estupro_de_vulneravel": "crimes_contra_crianca",
    "estupro_vulneravel": "crimes_contra_crianca",
    "crime_contra_crianca": "crimes_contra_crianca",
    "crime_organizado": "organizacao_criminosa",
    "associacao_criminosa": "organizacao_criminosa",
    "comercio_ilegal": "contrabando_descaminho",
    "contrabando": "contrabando_descaminho",
    "sequestro_bens": "bloqueio_bens",
    "sequestro_de_bens": "bloqueio_bens",
    "bloqueio_de_valores": "bloqueio_bens",
    "sequestro_indisponibilidade_valores_veiculos_imoveis": "bloqueio_bens",
    "caixa_2_campanha_eleitoral": "crime_eleitoral",
    "captacao_ilicita_sufragio": "crime_eleitoral",
    "venda_voto": "crime_eleitoral",
    "compra_voto": "crime_eleitoral",
    "colusao": "corrupcao_desvio",
    "fraude_publica": "corrupcao_desvio",
    "fraude_contratacao": "corrupcao_desvio",
    "fraude_em_processos_licitatorios": "corrupcao_desvio",
    "fraude_licitacao": "corrupcao_desvio",
    "desvio_recurso_publico": "corrupcao_desvio",
    "desvio_recursos": "corrupcao_desvio",
    "desvio_recursos_publicos": "corrupcao_desvio",
    "desvio_verbas_publicas": "corrupcao_desvio",
    "desvio_publico": "corrupcao_desvio",
    "abuso_de_poder": "corrupcao_desvio",
    "abuso_de_poder_publico": "corrupcao_desvio",
    "abuso_publico_financeiro": "corrupcao_desvio",
    "contratacao_direta_ilegal": "corrupcao_desvio",
    "fraude_a_licitacao": "corrupcao_desvio",
    "cartel": "corrupcao_desvio",
    "negociao_decisao_judicial": "corrupcao_desvio",
    "negociacao_decisao_judicial": "corrupcao_desvio",
    "obstrucao_de_investigacao": "corrupcao_desvio",
    "obstrucao_justica": "corrupcao_desvio",
    "modificacao_contrato_administrativo": "corrupcao_desvio",
    "negociacao_de_decisoes_judiciais": "corrupcao_desvio",
    "exploracao_de_prestigio": "corrupcao_desvio",
    "exploracao_prestigio": "corrupcao_desvio",
    "insercao_dados_falsos": "corrupcao_desvio",
    "peculato": "corrupcao_desvio",
    "peculato_digital": "desvio_postal",
    "falsificacao_documental": "falsidade_documental",
    "falsificacao_documento": "falsidade_documental",
    "falsificacao_documentos": "falsidade_documental",
    "falsificacao": "falsidade_documental",
    "falsificacao_documento_publico": "falsidade_documental",
    "falsificacao_sinal_publico": "falsidade_documental",
    "fraude_documental": "falsidade_documental",
    "apropriacao_identidade": "falsidade_documental",
    "falsidade_documental": "falsificacoes",
    "falsificacao_produto": "falsificacoes",
    "integacao_forcas_seguranca": "cooperacao_interagencias",
    "integracao_forcas_seguranca": "cooperacao_interagencias",
    "atuacao_integrada": "cooperacao_interagencias",
    "trafico_de_drogas": "trafico_drogas",
    "trafico_de_armas": "trafico_armas",
    "posse_ilica_arma_fogo": "posse_irregular_arma_fogo",
    "posse_irregular_arma_fogo": "crimes_armas",
    "trafico_armas": "crimes_armas",
    "desenvolver_clandestinamente_atividades_telecomunica": "desenvolvimento_clandestino_atividade_telecomunicacao",
    "desenvolver_clandestinamente_atividades_telecomunicacao": "desenvolvimento_clandestino_atividade_telecomunicacao",
    "desenvolvimento_clandestino_telecomunicacao": "desenvolvimento_clandestino_atividade_telecomunicacao",
    "crime_gerir_fraudulentamente_instituicao_financeira": "gestao_fraudulenta",
    "crime_operar_sem_autorizacao_instituicao_financeira": "gestao_fraudulenta",
    "gestao_fraudulenta": "crimes_sistema_financeiro",
    "negociacao_valores_mobiliarios": "crimes_sistema_financeiro",
    "cambio_ilegal": "crimes_sistema_financeiro",
    "fraude_eletronica": "fraude_bancaria_cibernetica",
    "fraude_electronica": "fraude_bancaria_cibernetica",
    "fraude_financeira": "fraude_bancaria_cibernetica",
    "fraude_bancaria": "fraude_bancaria_cibernetica",
    "fraude_informatica": "fraude_bancaria_cibernetica",
    "fraude_em_operacao_financeira": "fraude_bancaria_cibernetica",
    "fraude_informacoes_publicas": "fraude_bancaria_cibernetica",
    "fraude_financiamento_veiculos": "fraude_bancaria_cibernetica",
    "estelionato_majorado": "fraude_bancaria_cibernetica",
    "ataque_cibernetico": "fraude_bancaria_cibernetica",
    "estelionato": "fraude_bancaria_cibernetica",
    "fraude": "fraude_bancaria_cibernetica",
    "fraude_bancaria_cibernetica": "crimes_ciberneticos_financeiros",
    "invasao_sistema": "crimes_ciberneticos_financeiros",
    "fraude_a_posentadorias": "fraude_previdenciaria",
    "dano_a_floresta_de_preservacao_permanente": "crimes_ambientais",
    "dano_floresta_preservacao": "crimes_ambientais",
    "comercializacao_ilica_animales_silvestres": "crimes_ambientais",
    "crime_desflorestamento": "crimes_ambientais",
    "desflorestamento": "crimes_ambientais",
    "desflorestacao": "crimes_ambientais",
    "desmatamento_ilegal": "crimes_ambientais",
    "pescaria_ilica": "crimes_ambientais",
    "pescaria_irregular": "crimes_ambientais",
    "invasao_reserva": "crimes_ambientais",
    "pesca_irregular": "crimes_ambientais",
    "invasao_terras_publicas": "crimes_ambientais",
    "extracao_recursos_minerais_sem_autorizacao": "mineracao_irregular",
    "usurpacao_mat_prima_uniao": "mineracao_irregular",
    "usurpacao_materia_prima": "mineracao_irregular",
    "usurpacao_material_mineral": "mineracao_irregular",
    "usurpacao_bens_da_uniao": "crimes_ambientais",
    "mineracao_irregular": "crimes_ambientais",
    "provocacao_incendio_vegetacao": "crimes_ambientais",
    "incendio": "crimes_ambientais",
    "incendio_culposo": "crimes_ambientais",
    "trabalho_analog_escravidao": "trabalho_escravo_trafico_pessoas",
    "trabalho_escravo": "trabalho_escravo_trafico_pessoas",
    "trafico_pessoas": "trabalho_escravo_trafico_pessoas",
    "trafico_internacional_orgaos_humanos": "trabalho_escravo_trafico_pessoas",
    "migracao_ilegal": "exploracao_pessoas",
    "trabalho_escravo_trafico_pessoas": "exploracao_pessoas",
    "publicacao_conteudos_racistas_neonazistas": "apologia_nazismo",
    "publicacao_conteudos_racistas": "apologia_nazismo",
    "comercializacao_medicamentos_nao_autorizado": "comercializacao_medicamentos_nao_autorizados",
    "comercializacao_ilica": "comercializacao_medicamentos_nao_autorizados",
    "promocao_migracao_ilegal": "migracao_ilegal",
    "reintegragao_posse": "reintegracao_posse",
    "furto": "roubo_furto",
    "furto_qualificado": "roubo_furto",
    "roubo": "roubo_furto",
    "roubos": "roubo_furto",
    "latrocinio": "roubo_furto",
    "homicidios": "homicidio",
    "trafico_drogos": "trafico_drogas",
    "trafico_interestadual_drogas": "trafico_drogas",
    "fraude_eleitoral": "crime_eleitoral",
    "divulgacao_fatos_inveridicos": "crime_eleitoral",
    "violencia_politica_genero": "crime_eleitoral",
    "exploracao_jogos_azar": "jogos_azar",
    "exploracao_ilegal_maquinas_elettronicas": "jogos_azar",
    "venda_ilica_lotis": "jogos_azar",
    "venda_compra_ilica_lotis": "jogos_azar",
    "exercicio_irregular_atividade_seguranca_privada": "seguranca_privada_irregular",
    "manter_vigilantes_cursos_vencidos": "seguranca_privada_irregular",
    "manter_vigilantes_sem_curso": "seguranca_privada_irregular",
}

CLASSIFICATION_HIERARCHY = {
    "crimes_contra_crianca": (
        "abuso_sexual_infantil",
        "pornografia_infantil",
        "exploracao_sexual_infantil",
        "estupro_de_vulneravel",
    ),
    "crimes_ambientais": (
        "desmatamento_ilegal",
        "garimpo_ilegal",
        "mineracao_irregular",
        "pesca_irregular",
        "provocacao_incendio_vegetacao",
        "trafico_animais_silvestres",
        "usurpacao_bens_da_uniao",
    ),
    "crimes_sistema_financeiro": (
        "gestao_fraudulenta",
        "negociacao_valores_mobiliarios",
        "cambio_ilegal",
    ),
    "crimes_ciberneticos_financeiros": (
        "fraude_bancaria_cibernetica",
        "fraude_eletronica",
        "invasao_sistema",
    ),
    "crimes_armas": (
        "posse_irregular_arma_fogo",
        "trafico_armas",
    ),
    "exploracao_pessoas": (
        "trabalho_escravo_trafico_pessoas",
        "migracao_ilegal",
    ),
    "roubo_furto": (
        "furto",
        "furto_qualificado",
        "roubo",
        "latrocinio",
    ),
    "falsificacoes": (
        "falsidade_documental",
        "falsificacao_produto",
    ),
}

TERM_STOPWORDS = {
    "a", "ao", "aos", "as", "ate", "com", "contra", "da", "das", "de", "do", "dos", "e", "em",
    "na", "nas", "no", "nos", "o", "os", "ou", "para", "pela", "pelo", "por", "que", "sem",
    "sob", "sobre", "uma", "um", "policia", "federal", "operacao", "operacoes", "crime", "crimes",
    "apura", "apuracao", "investiga", "investigacao", "combate", "repressao", "deflagrou", "foram", "foi", "sao",
    "acao", "conjunta", "entre", "durante", "houve", "manha", "nesta", "neste", "sexta", "feira",
    "cerca", "policiais", "veiculo", "veiculos", "grande", "conjunto", "referencia", "branco",
    "contou", "apoio", "atuacao", "atividade", "irregular", "inves", "jargao", "juridico", "significa",
}

BAD_LEARNED_PATTERN_TERMS = {
    "assessoria", "brasil", "comunicacao", "contato", "email", "gov", "hoje", "http", "https",
    "imprensa", "file", "mail", "mailto", "nesta", "neste", "nome", "refere", "telefone",
    "telefones", "users", "www", "fones", "srto", "srdf", "srmg", "srpb", "srsc", "srpi",
    "korff",
}

CRIME_RULE_DEFS = (
    ("lavagem_dinheiro", (r"\blavagem de (?:dinheiro|capitais)\b", r"\bocultacao de bens\b", r"\bevasao de divisas\b", r"\borganizacao criminosa.*\bmovimentacao financeira\b"), 1.2),
    ("trafico_drogas", (r"\btrafico (?:internacional )?de drogas\b", r"\bentorpecentes?\b", r"\bmaconha\b", r"\bcocaina\b", r"\bcrack\b", r"\bskunk\b"), 1.15),
    ("crimes_armas", (r"\btrafico (?:internacional )?de armas\b", r"\bcomercio ilegal de armas\b", r"\barmas de fogo\b", r"\bmunicoes\b", r"\bposse irregular de arma de fogo\b", r"\bporte ilegal de arma de fogo\b", r"\barmas? de fogo sem autorizacao\b"), 1.15),
    ("crimes_ambientais", (r"\bcrimes? ambientais?\b", r"\bprotecao ambiental\b", r"\bgarimpo ilegal\b", r"\bdesmatamento\b", r"\bdesflorestamento\b", r"\bdesflorestacao\b", r"\bpesca ilegal\b", r"\bpesca irregular\b", r"\bextracao (?:ilegal|ilicita) de (?:ouro|minerios?|madeira)\b", r"\bextracao ilegal\b", r"\bextracao ilicita\b", r"\bmadeira ilegal\b", r"\bmineracao ilegal\b", r"\bmineracao irregular\b", r"\busurpacao de bens da uniao\b", r"\bretirada ilegal de moedas antigas\b", r"\bcomercio ilegal de animais silvestres\b", r"\banimais silvestres\b", r"\bflora nativa\b", r"\bfloresta de preservacao permanente\b"), 1.1),
    ("crime_eleitoral", (r"\bcrimes? eleitorais?\b", r"\bcompra de votos\b", r"\bcompra de voto\b", r"\bvenda de votos\b", r"\bvenda de voto\b", r"\bcaptacao ilicita de sufragio\b", r"\bcaixa dois eleitoral\b", r"\bcaixa 2 eleitoral\b", r"\bpropaganda eleitoral irregular\b"), 1.2),
    ("corrupcao_desvio", (r"\bcorrupcao\b", r"\bdesvios? em financiamentos?\b", r"\bdesvio de (?:recursos|verbas|dinheiro publico|recursos publicos|valores|verbas publicas)\b", r"\bfraudes? em licitac(?:ao|oes)\b", r"\bfraudes? licitatorias?\b", r"\bfraudes? e apura desvios? de recursos\b", r"\blicitac(?:ao|oes) fraudulenta", r"\bprocessos? licitatorios?.*fraud", r"\bcontratac(?:ao|oes) publica.*fraud", r"\bcontratos? publicos?.*fraud", r"\bfraudes? em contratos?\b", r"\bcontratos?.{0,80}fraud", r"\bcrimes? contra (?:a )?administracao publica\b", r"\bfundos? de pensao.*fraud", r"\bfraudes? a fundos? de pensao\b", r"\bcompra de insumos.*fraud", r"\bconcessao de titulos? de terras publicas\b", r"\bviolacao de sigilo funcional\b", r"\bobstrucao de justica\b", r"\bformacao de cartel\b", r"\bcartel\b", r"\bcolusao\b", r"\bpeculato\b", r"\bsuperfaturamento\b", r"\bvantagens? indevidas?\b", r"\bpropina\b"), 1.45),
    ("crimes_contra_crianca", (r"\babuso sexual (?:infantil|infantojuvenil|de criancas|de adolescentes)\b", r"\bexploracao sexual infantil\b", r"\bpedofilia\b", r"\bestupro de vulneravel\b", r"\bcondenado por estupro\b", r"\bpornografia infantil\b", r"\bpornografia infantojuvenil\b", r"\bconteudo pornografico infantil\b", r"\bconteudo pornografico infantojuvenil\b", r"\bimagens pornograficas de criancas\b", r"\bimagens pornograficas envolvendo menores\b", r"\bcompartilhamento de imagens pornograficas envolvendo menores\b", r"\bvideos pornograficos de criancas\b", r"\bdivulgacao de imagens de abuso sexual infantil\b", r"\bdisseminacao de pornografia infantil\b", r"\bdisseminacao de pornografia envolvendo criancas\b", r"\bpornografia envolvendo criancas\b", r"\bpornografia envolvendo criancas e adolescentes\b"), 1.4),
    ("contrabando_descaminho", (r"\bcontrabando\b", r"\bdescaminho\b", r"\bmercadorias estrangeiras\b", r"\bimportacao irregular\b", r"\bcigarros? (?:contrabandeados|falsificados|eletronicos)\b", r"\bcomercio ilegal de cigarros?\b", r"\bcomercio irregular de mercadorias estrangeiras\b"), 1.1),
    ("crimes_ciberneticos_financeiros", (r"\bfraudes? bancarias?\b", r"\bestelionato\b", r"\bestelionato majorado\b", r"\bgolpes?\b", r"\bcrimes? ciberneticos?\b", r"\bphishing\b", r"\binternet banking\b", r"\binvasao de dispositivo\b", r"\binvasao de sistema\b", r"\bacesso nao autorizado\b", r"\bsistemas? invadidos?\b", r"\bfraudes? de financiamento rural\b", r"\bfraudes? em financiamentos? de veiculos\b", r"\bfraude em financiamento de veiculos\b", r"\bfraudes? de emprestimo consignado\b", r"\bfraudes? em emprestimos? consignados?\b", r"\bfraudes? no saque de precatorios\b", r"\bfraudes? no recebimento de precatorios\b", r"\bfraudava auxilio emergencial\b"), 1.3),
    ("exploracao_pessoas", (r"\btrabalho (?:analogo ao de )?escravo\b", r"\bcondicoes degradantes\b", r"\btrafico de pessoas\b", r"\baliciamento de trabalhadores\b", r"\bmigracao ilegal\b", r"\bpromocao de migracao ilegal\b", r"\bimigracao ilegal\b", r"\bentrada ilegal de estrangeiros\b"), 1.2),
    ("organizacao_criminosa", (r"\borganizacao criminosa\b", r"\bassociacao criminosa\b", r"\bfaccao criminosa\b", r"\bmilicia\b"), 0.65),
    ("falsificacoes", (r"\bfalsidade (?:ideologica|documental)\b", r"\bfalsificac(?:ao|oes) de documentos?\b", r"\bdocumentos? falsos?\b", r"\bpassaporte falso\b", r"\bmoeda falsa\b", r"\bcedulas? falsas?\b", r"\bcertidao falsa\b", r"\bdiplomas? falsos?\b", r"\bfalsificac(?:ao|oes) (?:e venda de )?diplomas?\b", r"\bfalsificac(?:ao|oes) de sinal publico\b", r"\bsinal publico\b", r"\bprodutos? falsificados?\b", r"\bfalsificacao de produtos?\b", r"\bproduto adulterado\b", r"\bmercadorias? falsificadas?\b"), 1.3),
    ("apologia_nazismo", (r"\bapologia ao nazismo\b", r"\bideologias? nazistas?\b", r"\bsimbolos? nazistas?\b", r"\bconteudo neonazista\b"), 1.35),
    ("comercializacao_medicamentos_nao_autorizados", (r"\bmedicamentos? sem registro\b", r"\bmedicamentos? nao autorizados?\b", r"\bcomercializacao irregular de medicamentos?\b", r"\bremedios? falsificados?\b", r"\bproduto destinado a fim terapeutico\b", r"\bprodutos?.{0,80}fim terapeutico\b"), 1.3),
    ("desenvolvimento_clandestino_atividade_telecomunicacao", (r"\batividade clandestina de telecomunicacao\b", r"\btelecomunicacao clandestina\b", r"\bservico clandestino de telecomunicacao\b", r"\boperacao clandestina de radio\b"), 1.35),
    ("desvio_postal", (r"\bdesvio de encomendas?\b", r"\bdesvio postal\b", r"\bfraudes? postais?\b", r"\bsubtracao de objetos postais\b", r"\bobjetos postais desviados\b"), 1.35),
    ("exercicio_ilegal_profissao", (r"\bexercicio ilegal da profissao\b", r"\bfalso medico\b", r"\bfalsa profissao\b", r"\batuacao profissional ilegal\b"), 1.25),
    ("fraude_fiscal", (r"\bfraude fiscal\b", r"\bsonegacao fiscal\b", r"\bcrimes? tributarios?\b", r"\bsonegacao de impostos?\b"), 1.3),
    ("fraude_previdenciaria", (r"\bfraudes? previdenciarias?\b", r"\bfraudes? (?:contra|no|ao) inss\b", r"\bestelionato previdenciario\b", r"\bbeneficios? previdenciarios?.*fraud", r"\bfraude.*beneficios? previdenciarios?\b", r"\bfraude.*recursos do inss\b", r"\bprevidencia(?:s)? municipa(?:l|is).{0,120}fraud", r"\bfundos? previdenciarios?.*fraud", r"\bfraudes? ao fundo de amparo ao trabalhador\b", r"\bfraudes? na concessao de seguro-desemprego\b", r"\bfraudes? previdenciarias? no amapa\b", r"\bbpc\b", r"\bloas\b", r"\bauxilio emergencial.*fraud"), 1.55),
    ("crimes_sistema_financeiro", (r"\bgestao fraudulenta\b", r"\bgestao temeraria\b", r"\binstituicao financeira.*fraudulenta\b", r"\bfraudes? em instituicao financeira\b", r"\bcrimes? contra o sistema financeiro nacional\b", r"\bconsorcio sem registro\b", r"\batividade de consorcio sem registro\b", r"\bsem registro pelo bacen\b", r"\bvalores mobiliarios\b", r"\bnegociacao irregular de valores\b", r"\boferta irregular de investimento\b", r"\bmercado de capitais\b", r"\bcambio ilegal\b"), 1.35),
    ("homicidio", (r"\bhomicidio\b", r"\bhomicidios\b", r"\bmandante de homicidio\b", r"\btentativa de homicidio\b"), 1.25),
    ("crimes_ambientais", (r"\bmineracao irregular\b", r"\bmineracao ilegal\b", r"\bgarimpo irregular\b", r"\bgarimpo ilegal\b", r"\bincendio em vegetacao\b", r"\bincendio criminoso\b", r"\bqueimada ilegal\b", r"\bprovocar incendio\b"), 1.25),
    ("radiodifusao_irregular", (r"\bradiodifusao irregular\b", r"\bradio clandestina\b", r"\bradio pirata\b", r"\bestacao de radio clandestina\b"), 1.35),
    ("roubo_furto", (r"\broubo\b", r"\broubos\b", r"\blatrocinio\b", r"\bassalto\b", r"\bfurto\b", r"\bfurtos\b", r"\bfurto qualificado\b", r"\bsubtracao\b", r"\barrombamento\b", r"\barrombava cofres\b", r"\bcofres da caixa\b"), 1.2),
    ("ameaca", (r"\bameaca\b", r"\bameacas\b", r"\bameacar\b", r"\bameacou\b", r"\bameacas de morte\b"), 1.2),
    ("extorsao", (r"\bextorsao\b", r"\bextorquir\b", r"\bchantagem\b"), 1.25),
    ("fraude_concurso_publico", (r"\bfraude em concurso publico\b", r"\bfraude em certame publico\b", r"\bfraudes? em concursos?\b", r"\bcertame publico.*fraud"), 1.3),
    ("seguranca_privada_irregular", (r"\bseguranca privada irregular\b", r"\bvigilantes? sem curso\b", r"\bcursos? vencidos?\b", r"\bempresa de seguranca privada.*irregular\b"), 1.2),
    ("jogos_azar", (r"\bjogos? de azar\b", r"\bexploracao de jogos? de azar\b", r"\bmaquinas? caca-niqueis\b", r"\bloteria ilegal\b"), 1.2),
    ("violacao_direito_autoral", (r"\bviolacao de direito autoral\b", r"\bdireitos? autorais?\b", r"\bpirataria\b"), 1.2),
    ("terrorismo", (r"\bterrorismo\b", r"\batos? terroristas?\b", r"\bataques? terroristas?\b"), 1.25),
    ("reintegracao_posse", (r"\breintegracao de posse\b", r"\bcumprimento de reintegracao\b"), 1.05),
    ("uso_indevido_informacao_privilegiada", (r"\binformacao privilegiada\b", r"\binsider trading\b", r"\buso indevido de informacao\b"), 1.35),
    ("usurpacao_atividade_policial", (r"\busurpacao de funcao publica\b", r"\busurpacao de atividade policial\b", r"\bfalso policial\b"), 1.3),
)

MODUS_RULE_DEFS = (
    ("busca_apreensao", (r"\bbusca e apreensao\b", r"\bmandados? de busca\b"), 1.0),
    ("prisao", (r"\bprisao (?:preventiva|temporaria|em flagrante)\b", r"\bmandados? de prisao\b", r"\bpres[oa]s?\b"), 1.0),
    ("bloqueio_bens", (r"\bbloqueio de bens\b", r"\bsequestro de bens\b", r"\bindisponibilidade de bens\b"), 1.0),
    ("fiscalizacao", (r"\bfiscalizacao\b", r"\binspecao\b", r"\bvistoria\b"), 1.0),
    ("atuacao_online", (r"\binternet\b", r"\brede social\b", r"\bwhatsapp\b", r"\btelegram\b", r"\bonline\b"), 1.0),
    ("cooperacao_interagencias", (r"\breceita federal\b", r"\bibama\b", r"\bfunai\b", r"\bprf\b", r"\bficco\b", r"\bgaeco\b", r"\bforcas de seguranca\b", r"\bforca integrada\b"), 1.0),
    ("fronteira_transnacional", (r"\bfronteira\b", r"\bparaguai\b", r"\bbolivia\b", r"\bargentina\b", r"\btransnacional\b"), 1.0),
    ("resgate_vitimas", (r"\bresgate\b", r"\bvitimas?\b", r"\btrabalhadores resgatados\b"), 1.0),
    ("desarticulacao_rede", (r"\bdesarticul", r"\besquema criminoso\b", r"\bquadrilha\b", r"\brede criminosa\b"), 1.0),
    ("combate_financeiro", (r"\bmovimentacao financeira\b", r"\bcontas bancarias\b", r"\bsigilo bancario\b"), 1.0),
    ("cumprimento_mandado", (r"\bcumprimento de mandados?\b", r"\bmandado judicial\b", r"\bmandados? cumpridos?\b"), 1.15),
    ("criacao_empresa_fantasma", (r"\bempresas? fantasmas?\b", r"\bempresa de fachada\b", r"\bpessoas juridicas de fachada\b"), 1.25),
    ("exames_periciais", (r"\bexames? periciais?\b", r"\bpericia criminal\b", r"\blaudo pericial\b"), 1.2),
    ("inclusao_falsos_entrevistadores", (r"\bfalsos? entrevistadores?\b", r"\binclusao de falsos entrevistadores\b"), 1.3),
    ("processos_punitivos", (r"\bprocessos? punitivos?\b", r"\bprocedimento administrativo punitivo\b", r"\bprocesso administrativo sancionador\b"), 1.2),
    ("suspensao_atividades", (r"\bsuspensao das atividades\b", r"\batividades suspensas\b", r"\binterdicao de atividades\b"), 1.2),
    ("comercializacao", (r"\bcomercializacao\b", r"\bvenda ilegal\b", r"\bcomercio ilegal\b"), 0.9),
)
