from __future__ import annotations

LABEL_ALIASES = {
    "crime_organizado": "organizacao_criminosa",
    "associacao_criminosa": "organizacao_criminosa",
    "comercio_ilegal": "contrabando_descaminho",
    "contrabando": "contrabando_descaminho",
    "sequestro_bens": "bloqueio_bens",
    "sequestro_de_bens": "bloqueio_bens",
    "bloqueio_de_valores": "bloqueio_bens",
    "sequestro_indisponibilidade_valores_veiculos_imoveis": "bloqueio_bens",
    "caixa_2_campanha_eleitoral": "crime_eleitoral",
    "captacao_ilicita_sufragio": "crime_eleitoral",
    "venda_voto": "crime_eleitoral",
    "compra_voto": "crime_eleitoral",
    "colusao": "corrupcao_desvio",
    "fraude_publica": "corrupcao_desvio",
    "fraude_contratacao": "corrupcao_desvio",
    "fraude_em_processos_licitatorios": "corrupcao_desvio",
    "fraude_licitacao": "corrupcao_desvio",
    "desvio_recurso_publico": "corrupcao_desvio",
    "desvio_recursos": "corrupcao_desvio",
    "desvio_recursos_publicos": "corrupcao_desvio",
    "modificacao_contrato_administrativo": "corrupcao_desvio",
    "negociacao_de_decisoes_judiciais": "corrupcao_desvio",
    "exploracao_prestigio": "corrupcao_desvio",
    "insercao_dados_falsos": "corrupcao_desvio",
    "falsificacao_documental": "falsidade_documental",
    "falsificacao_documento": "falsidade_documental",
    "falsificacao_documentos": "falsidade_documental",
    "falsificacao": "falsidade_documental",
    "falsificacao_documento_publico": "falsidade_documental",
    "falsificacao_sinal_publico": "falsidade_documental",
    "fraude_documental": "falsidade_documental",
    "apropriacao_identidade": "falsidade_documental",
    "pornografia_infantojuvenil": "pornografia_infantil",
    "pornografia_infantil_online": "pornografia_infantil",
    "integacao_forcas_seguranca": "cooperacao_interagencias",
    "integracao_forcas_seguranca": "cooperacao_interagencias",
    "atuacao_integrada": "cooperacao_interagencias",
    "trafico_de_drogas": "trafico_drogas",
    "trafico_de_armas": "trafico_armas",
    "posse_ilica_arma_fogo": "posse_irregular_arma_fogo",
    "desenvolver_clandestinamente_atividades_telecomunica": "desenvolvimento_clandestino_atividade_telecomunicacao",
    "desenvolver_clandestinamente_atividades_telecomunicacao": "desenvolvimento_clandestino_atividade_telecomunicacao",
    "desenvolvimento_clandestino_telecomunicacao": "desenvolvimento_clandestino_atividade_telecomunicacao",
    "crime_gerir_fraudulentamente_instituicao_financeira": "gestao_fraudulenta",
    "crime_operar_sem_autorizacao_instituicao_financeira": "gestao_fraudulenta",
    "fraude_eletronica": "fraude_bancaria_cibernetica",
    "ataque_cibernetico": "fraude_bancaria_cibernetica",
    "estelionato": "fraude_bancaria_cibernetica",
    "fraude": "fraude_bancaria_cibernetica",
    "dano_a_floresta_de_preservacao_permanente": "crimes_ambientais",
    "dano_floresta_preservacao": "crimes_ambientais",
    "comercializacao_ilica_animales_silvestres": "crimes_ambientais",
    "pesca_irregular": "crimes_ambientais",
    "invasao_terras_publicas": "crimes_ambientais",
    "usurpacao_materia_prima": "mineracao_irregular",
    "usurpacao_material_mineral": "mineracao_irregular",
    "trabalho_analog_escravidao": "trabalho_escravo_trafico_pessoas",
    "trafico_pessoas": "trabalho_escravo_trafico_pessoas",
    "trafico_internacional_orgaos_humanos": "trabalho_escravo_trafico_pessoas",
    "publicacao_conteudos_racistas_neonazistas": "apologia_nazismo",
    "comercializacao_medicamentos_nao_autorizado": "comercializacao_medicamentos_nao_autorizados",
    "promocao_migracao_ilegal": "migracao_ilegal",
    "reintegragao_posse": "reintegracao_posse",
}

TERM_STOPWORDS = {
    "a", "ao", "aos", "as", "ate", "com", "contra", "da", "das", "de", "do", "dos", "e", "em",
    "na", "nas", "no", "nos", "o", "os", "ou", "para", "pela", "pelo", "por", "que", "sem",
    "sob", "sobre", "uma", "um", "policia", "federal", "operacao", "operacoes", "crime", "crimes",
    "apura", "apuracao", "investiga", "investigacao", "combate", "repressao", "deflagrou", "foram", "foi", "sao",
    "acao", "conjunta", "entre", "durante", "houve", "manha", "nesta", "neste", "sexta", "feira",
    "cerca", "policiais", "veiculo", "veiculos", "grande", "conjunto", "referencia", "branco",
    "contou", "apoio", "atuacao", "atividade", "irregular", "inves", "jargao", "juridico", "significa",
}

BAD_LEARNED_PATTERN_TERMS = {
    "assessoria", "brasil", "comunicacao", "contato", "email", "gov", "hoje", "http", "https",
    "imprensa", "file", "mail", "mailto", "nesta", "neste", "nome", "refere", "telefone",
    "telefones", "users", "www", "fones", "srto", "srdf", "srmg", "srpb", "srsc", "srpi",
    "korff",
}

CRIME_RULE_DEFS = (
    ("lavagem_dinheiro", (r"\blavagem de (?:dinheiro|capitais)\b", r"\bocultacao de bens\b", r"\bevasao de divisas\b", r"\borganizacao criminosa.*\bmovimentacao financeira\b"), 1.2),
    ("trafico_drogas", (r"\btrafico (?:internacional )?de drogas\b", r"\bentorpecentes?\b", r"\bmaconha\b", r"\bcocaina\b", r"\bcrack\b", r"\bskunk\b"), 1.15),
    ("trafico_armas", (r"\btrafico (?:internacional )?de armas\b", r"\bcomercio ilegal de armas\b", r"\barmas de fogo\b", r"\bmunicoes\b"), 1.1),
    ("crimes_ambientais", (r"\bcrimes? ambientais?\b", r"\bgarimpo ilegal\b", r"\bdesmatamento\b", r"\bpesca ilegal\b", r"\bpesca irregular\b", r"\bextracao ilegal\b", r"\bmadeira ilegal\b", r"\bmineracao ilegal\b", r"\bcomercio ilegal de animais silvestres\b", r"\banimais silvestres\b", r"\bflora nativa\b", r"\bfloresta de preservacao permanente\b"), 1.1),
    ("crime_eleitoral", (r"\bcrimes? eleitorais?\b", r"\bcompra de votos\b", r"\bcompra de voto\b", r"\bvenda de votos\b", r"\bvenda de voto\b", r"\bcaptacao ilicita de sufragio\b", r"\bcaixa dois eleitoral\b", r"\bcaixa 2 eleitoral\b", r"\bpropaganda eleitoral irregular\b"), 1.2),
    ("corrupcao_desvio", (r"\bcorrupcao\b", r"\bdesvio de (?:recursos|verbas|dinheiro publico|recursos publicos|valores)\b", r"\bfraudes? em licitac(?:ao|oes)\b", r"\bfraudes? licitatorias?\b", r"\blicitac(?:ao|oes) fraudulenta", r"\bprocessos? licitatorios?.*fraud", r"\bcontratac(?:ao|oes) publica.*fraud", r"\bcontratos? publicos?.*fraud", r"\bcolusao\b", r"\bpeculato\b", r"\bsuperfaturamento\b", r"\bvantagens? indevidas?\b", r"\bpropina\b"), 1.45),
    ("abuso_sexual_infantil", (r"\babuso sexual (?:infantil|infantojuvenil|de criancas|de adolescentes)\b", r"\bexploracao sexual infantil\b", r"\bpedofilia\b", r"\bestupro de vulneravel\b"), 1.35),
    ("pornografia_infantil", (r"\bpornografia infantil\b", r"\bpornografia infantojuvenil\b", r"\bconteudo pornografico infantil\b", r"\bconteudo pornografico infantojuvenil\b", r"\bimagens pornograficas de criancas\b", r"\bvideos pornograficos de criancas\b", r"\bdivulgacao de imagens de abuso sexual infantil\b", r"\bdisseminacao de pornografia infantil\b"), 1.35),
    ("contrabando_descaminho", (r"\bcontrabando\b", r"\bdescaminho\b", r"\bmercadorias estrangeiras\b", r"\bimportacao irregular\b", r"\bcigarros? (?:contrabandeados|falsificados)\b"), 1.0),
    ("fraude_bancaria_cibernetica", (r"\bfraudes? bancarias?\b", r"\bestelionato\b", r"\bgolpes?\b", r"\bcrimes? ciberneticos?\b", r"\bphishing\b", r"\binternet banking\b", r"\binvasao de dispositivo\b"), 1.0),
    ("trabalho_escravo_trafico_pessoas", (r"\btrabalho (?:analogo ao de )?escravo\b", r"\bcondicoes degradantes\b", r"\btrafico de pessoas\b", r"\baliciamento de trabalhadores\b"), 1.2),
    ("organizacao_criminosa", (r"\borganizacao criminosa\b", r"\bassociacao criminosa\b", r"\bfaccao criminosa\b", r"\bmilicia\b"), 0.65),
    ("falsidade_documental", (r"\bfalsidade (?:ideologica|documental)\b", r"\bdocumentos? falsos?\b", r"\bpassaporte falso\b", r"\bmoeda falsa\b", r"\bcedulas? falsas?\b", r"\bcertidao falsa\b"), 1.0),
    ("apologia_nazismo", (r"\bapologia ao nazismo\b", r"\bideologias? nazistas?\b", r"\bsimbolos? nazistas?\b", r"\bconteudo neonazista\b"), 1.35),
    ("comercializacao_medicamentos_nao_autorizados", (r"\bmedicamentos? sem registro\b", r"\bmedicamentos? nao autorizados?\b", r"\bcomercializacao irregular de medicamentos?\b", r"\bremedios? falsificados?\b"), 1.3),
    ("desenvolvimento_clandestino_atividade_telecomunicacao", (r"\batividade clandestina de telecomunicacao\b", r"\btelecomunicacao clandestina\b", r"\bservico clandestino de telecomunicacao\b", r"\boperacao clandestina de radio\b"), 1.35),
    ("desvio_postal", (r"\bdesvio de encomendas?\b", r"\bdesvio postal\b", r"\bsubtracao de objetos postais\b", r"\bobjetos postais desviados\b"), 1.3),
    ("exercicio_ilegal_profissao", (r"\bexercicio ilegal da profissao\b", r"\bfalso medico\b", r"\bfalsa profissao\b", r"\batuacao profissional ilegal\b"), 1.25),
    ("falsificacao_produto", (r"\bprodutos? falsificados?\b", r"\bfalsificacao de produtos?\b", r"\bproduto adulterado\b", r"\bmercadorias? falsificadas?\b"), 1.25),
    ("fraude_fiscal", (r"\bfraude fiscal\b", r"\bsonegacao fiscal\b", r"\bcrimes? tributarios?\b", r"\bsonegacao de impostos?\b"), 1.3),
    ("fraude_previdenciaria", (r"\bfraudes? previdenciarias?\b", r"\bfraudes? (?:contra|no) inss\b", r"\bbeneficios? previdenciarios?.*fraud", r"\bfraude.*beneficios? previdenciarios?\b", r"\bbpc\b", r"\bloas\b", r"\bauxilio emergencial.*fraud"), 1.45),
    ("gestao_fraudulenta", (r"\bgestao fraudulenta\b", r"\bgestao temeraria\b", r"\binstituicao financeira.*fraudulenta\b"), 1.35),
    ("homicidio", (r"\bhomicidio\b", r"\bhomicidios\b", r"\bmandante de homicidio\b", r"\btentativa de homicidio\b"), 1.25),
    ("invasao_sistema", (r"\binvasao de sistema\b", r"\binvasao de dispositivo\b", r"\bacesso nao autorizado\b", r"\bsistemas? invadidos?\b"), 1.3),
    ("mineracao_irregular", (r"\bmineracao irregular\b", r"\bmineracao ilegal\b", r"\bgarimpo irregular\b", r"\bgarimpo ilegal\b"), 1.25),
    ("negociacao_valores_mobiliarios", (r"\bvalores mobiliarios\b", r"\bnegociacao irregular de valores\b", r"\boferta irregular de investimento\b", r"\bmercado de capitais\b"), 1.25),
    ("posse_irregular_arma_fogo", (r"\bposse irregular de arma de fogo\b", r"\bporte ilegal de arma de fogo\b", r"\barmas? de fogo sem autorizacao\b"), 1.3),
    ("provocacao_incendio_vegetacao", (r"\bincendio em vegetacao\b", r"\bincendio criminoso\b", r"\bqueimada ilegal\b", r"\bprovocar incendio\b"), 1.25),
    ("radiodifusao_irregular", (r"\bradiodifusao irregular\b", r"\bradio clandestina\b", r"\bradio pirata\b", r"\bestacao de radio clandestina\b"), 1.35),
    ("roubo", (r"\broubo\b", r"\broubos\b", r"\blatrocinio\b", r"\bassalto\b"), 1.2),
    ("furto", (r"\bfurto\b", r"\bfurtos\b", r"\bsubtracao\b", r"\barrombamento\b"), 1.15),
    ("ameaca", (r"\bameaca\b", r"\bameacas\b", r"\bameacar\b", r"\bameacou\b", r"\bameacas de morte\b"), 1.2),
    ("extorsao", (r"\bextorsao\b", r"\bextorquir\b", r"\bchantagem\b"), 1.25),
    ("fraude_concurso_publico", (r"\bfraude em concurso publico\b", r"\bfraude em certame publico\b", r"\bfraudes? em concursos?\b", r"\bcertame publico.*fraud"), 1.3),
    ("migracao_ilegal", (r"\bmigracao ilegal\b", r"\bpromocao de migracao ilegal\b", r"\bimigracao ilegal\b", r"\bentrada ilegal de estrangeiros\b"), 1.25),
    ("seguranca_privada_irregular", (r"\bseguranca privada irregular\b", r"\bvigilantes? sem curso\b", r"\bcursos? vencidos?\b", r"\bempresa de seguranca privada.*irregular\b"), 1.2),
    ("jogos_azar", (r"\bjogos? de azar\b", r"\bexploracao de jogos? de azar\b", r"\bmaquinas? caca-niqueis\b", r"\bloteria ilegal\b"), 1.2),
    ("violacao_direito_autoral", (r"\bviolacao de direito autoral\b", r"\bdireitos? autorais?\b", r"\bpirataria\b"), 1.2),
    ("terrorismo", (r"\bterrorismo\b", r"\batos? terroristas?\b", r"\bataques? terroristas?\b"), 1.25),
    ("reintegracao_posse", (r"\breintegracao de posse\b", r"\bcumprimento de reintegracao\b"), 1.05),
    ("uso_indevido_informacao_privilegiada", (r"\binformacao privilegiada\b", r"\binsider trading\b", r"\buso indevido de informacao\b"), 1.35),
    ("usurpacao_atividade_policial", (r"\busurpacao de funcao publica\b", r"\busurpacao de atividade policial\b", r"\bfalso policial\b"), 1.3),
)

MODUS_RULE_DEFS = (
    ("busca_apreensao", (r"\bbusca e apreensao\b", r"\bmandados? de busca\b"), 1.0),
    ("prisao", (r"\bprisao (?:preventiva|temporaria|em flagrante)\b", r"\bmandados? de prisao\b", r"\bpres[oa]s?\b"), 1.0),
    ("bloqueio_bens", (r"\bbloqueio de bens\b", r"\bsequestro de bens\b", r"\bindisponibilidade de bens\b"), 1.0),
    ("fiscalizacao", (r"\bfiscalizacao\b", r"\binspecao\b", r"\bvistoria\b"), 1.0),
    ("atuacao_online", (r"\binternet\b", r"\brede social\b", r"\bwhatsapp\b", r"\btelegram\b", r"\bonline\b"), 1.0),
    ("cooperacao_interagencias", (r"\breceita federal\b", r"\bibama\b", r"\bfunai\b", r"\bprf\b", r"\bficco\b", r"\bgaeco\b", r"\bforcas de seguranca\b", r"\bforca integrada\b"), 1.0),
    ("fronteira_transnacional", (r"\bfronteira\b", r"\bparaguai\b", r"\bbolivia\b", r"\bargentina\b", r"\btransnacional\b"), 1.0),
    ("resgate_vitimas", (r"\bresgate\b", r"\bvitimas?\b", r"\btrabalhadores resgatados\b"), 1.0),
    ("desarticulacao_rede", (r"\bdesarticul", r"\besquema criminoso\b", r"\bquadrilha\b", r"\brede criminosa\b"), 1.0),
    ("combate_financeiro", (r"\bmovimentacao financeira\b", r"\bcontas bancarias\b", r"\bsigilo bancario\b"), 1.0),
    ("cumprimento_mandado", (r"\bcumprimento de mandados?\b", r"\bmandado judicial\b", r"\bmandados? cumpridos?\b"), 1.15),
    ("criacao_empresa_fantasma", (r"\bempresas? fantasmas?\b", r"\bempresa de fachada\b", r"\bpessoas juridicas de fachada\b"), 1.25),
    ("exames_periciais", (r"\bexames? periciais?\b", r"\bpericia criminal\b", r"\blaudo pericial\b"), 1.2),
    ("inclusao_falsos_entrevistadores", (r"\bfalsos? entrevistadores?\b", r"\binclusao de falsos entrevistadores\b"), 1.3),
    ("processos_punitivos", (r"\bprocessos? punitivos?\b", r"\bprocedimento administrativo punitivo\b", r"\bprocesso administrativo sancionador\b"), 1.2),
    ("suspensao_atividades", (r"\bsuspensao das atividades\b", r"\batividades suspensas\b", r"\binterdicao de atividades\b"), 1.2),
    ("comercializacao", (r"\bcomercializacao\b", r"\bvenda ilegal\b", r"\bcomercio ilegal\b"), 0.9),
)
